### ISSUE TITLE
Clarify supported Python version(s)

### ISSUE THREAD

**Issue by AndrewSales** [robbert-harms/pyschematron#1]
Thank you for your implementation.

Can I suggest making the supported Python version(s) explicit in the README?

AFAICT, 3.12 is only mentioned in the code.

(Installation will succeed with `pip` under Python 3.10, but the installed package then appears to be incomplete on import; it fails under 3.13 with an `lxml` dependency error.)

**Comment by robbert-harms** [comment]
Hi Andrew,

Thank you for your comment, and thank you for adding PySchematron to your list of software packages. 

I added a comment to the README specifying the supported Python version, as you suggested. Older Python versions (3.11 and down) are not supported due to missing Python functionality. Newer versions I have not had the chance to test yet.

Closing this, as it appears to be resolved. Let me know if you find anything else.
