### ISSUE TITLE
Question: would a higher lxml work e.g. lxml>=5.1.0?

### ISSUE THREAD

**Issue by martin-honnen** [robbert-harms/pyschematron#2]
I am trying to use pyschematron with Pyodide which currently has the lxml 5.2.1 version "pre-compiled"/built-in.

That way at least Pyodide then stumbles over the pyschematron lxml~=5.1.0 requirement, giving an error `ValueError: Requested 'lxml~=5.1.0', but lxml==5.2.1 is already installed`.

Therefore I wonder whether pyschematron could change its lxml dependency to lxml>=5.1.0.

**Comment by robbert-harms** [comment]
Hi Martin, 

I could do that, but another bug report said it didn't work in Python 3.13 because of some lxml issue. In general I am a bit hesitant to give broad dependency specifications. 

Notwithstanding, I did test with lxml 5.2.1 and that seems to work with PySchematron. As such, I updated the dependency to 5.2.1. Please check out the recent PySchematron version, it should now work for you.

Best, Robbert

**Comment by martin-honnen** [comment]
Thanks a lot, it indeed works great now with Pyodide.
